disabled_rules:
  - identifier_name
  - line_length
opt_in_rules:
  - force_unwrapping
included:
  - ServiceWorkerContainer
cyclomatic_complexity:
  - 15
  - 30
function_body_length:
  - 50
  - 100
file_length:
  - 500
  - 800
#force_unwrapping: error
